services:
  app:
    build: .
    ports:
      - "4033:4033"
    volumes:
      - ./src:/app/src
      - ./target:/app/target
      - ~/.m2:/root/.m2
    environment:
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
      - SPRING_DEVTOOLS_LIVERELOAD_ENABLED=true
