version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4033:4033"
      - "35729:35729"
    volumes:
      - ./src:/app/src:ro
      - ./pom.xml:/app/pom.xml:ro
      - ./.env:/app/.env:ro
      - maven-cache:/root/.m2
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
      - SPRING_DEVTOOLS_LIVERELOAD_ENABLED=true
    restart: always
    command:
      [
        "./mvnw",
        "spring-boot:run",
        "-Dspring-boot.run.fork=false",
        "-Dspring.devtools.restart.enabled=true",
        "-Dspring.devtools.livereload.enabled=true",
      ]
    networks:
      - ohara

volumes:
  maven-cache:

networks:
  ohara:
    external: true
    name: ohara
